### ISSUE TITLE
Issue loading swagger-ui in micronaut 3.10.1 with http://localhost:8080/demo/swagger-ui

### ISSUE THREAD

**Issue by ak10o** [micronaut-projects/micronaut-starter#2031] opened 2023-08-31 09:54 UTC
### Description

I am facing the issue when invoking http://localhost:8080/demo/swagger-ui

It occurs in our production code when we migrated from Micronaut version 3.1.3 to 3.10.1. To reproduce this we used Micronaut Launch demo app.

### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create a micronaut demo app from https://micronaut.io/launch/
2. Select micronaut version 3.10.1
3. Add  OpenAPI and Swagger as part of the feature
4. Select java 11 , gradle as build tool and junit as test framework 
5. Modify the application.yml to `prefix` "demo" in the mapping attribute

micronaut:
  application:
    name: demo
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /demo/swagger/
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /demo/swagger-ui/
        
 6. Modified the openapi.properties
 
 swagger-ui.enabled=true
redoc.enabled=false
rapidoc.enabled=false
rapidoc.bg-color=#14191f
rapidoc.text-color=#aec2e0
rapidoc.sort-endpoints-by=method

micronaut.openapi.views.spec=mapping.path=/demo/swagger    

### Expected Behaviour

The swagger-ui page should be loaded when invoked with the url http://localhost:8080/demo/swagger-ui

### Actual Behaviour

The page is blank, when we inspected then we saw some 404 error

![image](https://github.com/micronaut-projects/micronaut-starter/assets/26184920/8eb75df0-53c1-4b3d-8072-331ac28c1a6c)

### Environment Information

- **Operating System**: Mac
- **Micronaut Version:** 3.10.1
- **JDK Version:** 11

Although with the below configuration we can load the swagger-ui with the url  http://localhost:8080/swagger-ui 

Application.yml 

micronaut:
  application:
    name: demo
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/

And openapi.properties

swagger-ui.enabled=true
redoc.enabled=false
rapidoc.enabled=false
rapidoc.bg-color=#14191f
rapidoc.text-color=#aec2e0
rapidoc.sort-endpoints-by=method

micronaut.openapi.views.spec=mapping.path=/swagger

**Comment by altro3** [comment] 2024-02-17 11:50
@ak10o If you have context path for your application, you also need to tell about it to micronaut-openapi annotation processor, because you changed path to javascript / css resource-files. Look here: https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html#swaggerui

![изображение](https://github.com/micronaut-projects/micronaut-starter/assets/48474279/9401a853-5fd0-444f-b228-f85f6c073db0)

You just need to add value to `openapi.properties` in your case:
```properties
swagger-ui.js.url=demo/swagger-ui
```

**Comment by altro3** [comment] 2024-02-17 11:51
@sdelamo You can close it, it's not a bug

**Closed as completed** 2024-02-20 11:16 UTC
